(print "Begin the Calculation")
(setf x (+ 10 5))
(print (+ "Hello" "World"))
(print "Answer is " x)
(print x " ADD " 15 " IS " (+ x 15))
(print x " SUB " 5 " IS " (- x 5))
(print "5 * 2 IS " (* 5 2))
(print "100 / 2 IS " (/ 100 2))
(print "1==1 IS " (== 1 1))
(print "HELLO == WORLD " (== "Hello" "World"))
(print "HELLO != WORLD " (!= "Hello" "World"))
(print "LENGTH OF HELLO IS " (len "Hello"))
(print "RAND(3) = " (rnd 3))
