(print "Begin the Calculation")
(setf x (+ 10 5))
(print (+ "Hello" "World"))
(print "Answer is " x)
(print x " ADD " 15 " IS " (+ x 15))
(print x " SUB " 5 " IS " (- x 5))
(print "5 * 2 IS " (* 5 2))
(print "100 / 2 IS " (/ 100 2))
